FROM jenkins:1.642.2
MAINTAINER kmilner@seven10storage.com
COPY bin/setup-docker-and-start-jenkins.sh /usr/local/bin/setup-docker-and-start-jenkins.sh
USER root
CMD ["/usr/local/bin/setup-docker-and-start-jenkins.sh"]